# Generated by Django 3.1.3 on 2021-02-23 22:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MusicToNotes', '0003_auto_20210116_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
