# Generated by Django 3.1.3 on 2021-03-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicToNotes', '0005_auto_20210307_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='using_file',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='using_recording',
            field=models.BooleanField(default=0),
        ),
    ]
